### ISSUE TITLE
Can the metric for nest_cooling be added?

### ISSUE THREAD

**Issue by jonlundy** [grdl/pronestheus#19]
Currently i only read a metric for `nest_heating` but it does not indicate a metric for `nest_cooling`

**Comment by klyubin** [comment]
It appears this project is not actively maintained -- the last commit is from Jun 2022 and my PRs against this repo have gone unanswered (TBH, it's fine, I don't expect the original maintainer to have to do this). I forked this repo some time ago as https://github.com/klyubin/pronestheus. My fork does contain `nest_cooling` and a few more things. I'm also hoping to add the scraping of Nest Temperature Sensors now that that experiment has been working fine for me for the past 6 months.

**Comment by jonlundy** [comment]
@klyubin very cool! thank you for the information.
