### ISSUE TITLE
How to get PRONESTHEUS_NEST_TOKEN

### ISSUE THREAD

**Issue by PehrGit** [grdl/pronestheus#2]
Hi,

This looks like a cool project but I'm not sure how to find the PRONESTHEUS_NEST_TOKEN. Any advice? Note: I've migrated to a Google account

**Comment by grdl** [comment]
Unfortunately, Google has killed the Nest Developer API :( https://developers.nest.com

As far as I know, if you have the old account, your API token will still work for some time. However, it is impossible to create new ones and the API will be "retired" soon.

**Comment by grdl** [comment]
Hi @PehrGit ,

I just learned that you can, in fact, access the Nest API via the new [Google Device Management API](https://developers.google.com/nest/device-access). 

I have released a new version of the exporter and updated the [README.md](https://github.com/grdl/pronestheus/#authentication) with instructions on how to Authenticate with the new API. It's not very straight-forward and Google charges a one-time $5 fee for that 😕
